version: "1.0"
stages:
  - release
steps:
  get_variables:
    tile: Variables
    image: alpine
    commands:
      - env
      - echo $CF_REPO_OWNER
      - echo $CF_REPO_NAME
      - echo $CF_BRANCH
  main_clone:
    title: Cloning repository
    type: git-clone
    arguments:
      git: github
      repo: "${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}"
      revision: "${{CF_BRANCH}}"
    stage: release
  build_image:
    title: Building container image
    type: build
    image_name: heathseals/argocd-tools
    tag: "${{CF_BRANCH}}"
    tags:
    - ${{CF_SHORT_REVISION}}
    - latest
    registry: heathseals
    stage: release
