name: 'Commit: Build and push image to nodata-artifacts Google Artifact Registry'
on:
  push:
    branches:
      - main
jobs:
  release:
    env:
      ARTIFACT_REGISTRY_PATH: 'us-west1-docker.pkg.dev/k8s-nodata/nodata-artifacts'
      IMAGE_NAME: 'argocd-tools'
      IMAGE_TAG: ${GITHUB_SHA}
      PUBLISHER_PREFIX: 'artifact'
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: google-auth
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/686723139082/locations/global/workloadIdentityPools/nodata/providers/github'
          service_account: '${{ env.PUBLISHER_PREFIX }}-publisher@k8s-nodata.iam.gserviceaccount.com'
      - name: Build image
        run: docker build --build-arg GITHUB_SHA -t "${{ env.ARTIFACT_REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" .
      - name: Authenticate to Google Artifact Registry and push image
        run: |
          gcloud --quiet auth configure-docker us-west1-docker.pkg.dev
          docker push ${{ env.ARTIFACT_REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
